export const IPC = {
  BACKEND_INVOKE: 'backend:invoke',
  BACKEND_STATUS: 'backend:status',
  BACKEND_NOTIFICATION: 'backend:notification',
  MONITOR_TELEMETRY: 'monitor:telemetry',
  MONITOR_SNAPSHOT: 'monitor:snapshot',
  PTY_CREATE: 'pty:create',
  PTY_WRITE: 'pty:write',
  PTY_RESIZE: 'pty:resize',
  PTY_KILL: 'pty:kill',
  PTY_DATA: 'pty:data',
  JUPYTER_START: 'jupyter:start',
  JUPYTER_STOP: 'jupyter:stop',
  JUPYTER_STATUS: 'jupyter:status',
  FS_OPEN_DIALOG: 'fs:openDialog',
  FS_SAVE_DIALOG: 'fs:saveDialog',
  FS_READ_DIR: 'fs:readDir',
  FS_READ_FILE: 'fs:readFile',
  FS_WRITE_FILE: 'fs:writeFile',
  UPDATER_DOWNLOAD: 'updater:download',
  UPDATER_INSTALL: 'updater:install',
  UPDATER_EVENT: 'updater:event',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',
  APP_HOME_DIR: 'app:homeDir'
} as const
